### ISSUE TITLE
missing 0.21.0 debian builds

### ISSUE THREAD

**Issue by jjo** [bitnami/bitnami-docker-nginx-ingress-controller#1]
**Description**

https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.21.0 fixes
http/2 security vulnerability issues, upstream build already available since >1week ago.

**Steps to reproduce the issue:**

Only `ol` builds are available as per
https://hub.docker.com/r/bitnami/nginx-ingress-controller/tags/

**Describe the results you expected:**

Have `bitnami/nginx-ingress-controller:0.21.0-rX` available.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

N/A

- Output of `docker info`:

N/A

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

N/A

**Comment by marcosbc** [comment]
We understand this issue was opened because there was a new release, 0.21.0. Currently the container for 0.23.0 is already published, so I'm closing this.
