### ISSUE TITLE
Enable brotli support

### ISSUE THREAD

**Issue by aeimer** [bitnami/bitnami-docker-nginx-ingress-controller#11]
**Description**

Would it be possible to enable the brotli capabilities for the btinami nginx ingress also?
Currently there is an error when I 
```yaml
config:
  enable-brotli: 'true'
```

Tested with `bitnami/nginx-ingress-controller:7.6.10`

Probably related => https://github.com/bitnami/bitnami-docker-nginx/issues/144

**Steps to reproduce the issue:**

1. Deploy ingress helmchart
2. Redeploy with the `config.enable-brotli: 'true'` set
3. [and so on...]

**Describe the results you received:**

```log
I0618 12:23:16.140404 1 controller.go:146] "Configuration changes detected, backend reload required"
E0618 12:23:16.229645 1 controller.go:158] Unexpected failure reloading the backend:

-------------------------------------------------------------------------------
Error: exit status 1
2021/06/18 12:23:16 [emerg] 2061#2061: dlopen() "/etc/nginx/modules/ngx_http_brotli_filter_module.so" failed (/etc/nginx/modules/ngx_http_brotli_filter_module.so: cannot open shared object file: No such file or directory) in /tmp/nginx-cfg766065183:7
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_brotli_filter_module.so" failed (/etc/nginx/modules/ngx_http_brotli_filter_module.so: cannot open shared object file: No such file or directory) in /tmp/nginx-cfg766065183:7
nginx: configuration file /tmp/nginx-cfg766065183 test failed

-------------------------------------------------------------------------------
I0618 12:23:16.229829 1 event.go:282] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ingress-main", Name:"nginx-ingress-ctrl-main-786664f4c-4gtbl", UID:"42c8e13b-8fa1-42d5-b6a3-8463bf9e33f2", APIVersion:"v1", ResourceVersion:"133058234", FieldPath:""}): type: 'Warning' reason: 'RELOAD' Error reloading NGINX:
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
We use kubernetes 1.20
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. I will open a task for investigation. As soon as we have more news, I will update this ticket.

**Comment by AlexisDucastel** [comment]
Any update about brotli activation ? We do reproduce this error message.

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. When we have more news, we will update the ticket.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of the nginx-ingress-controller chart that fixes the brotli issue

```
I have no name!@ngx-nginx-ingress-controller-58bfb8d754-r89f2:/opt/bitnami/nginx-ingress-controller$ ls /opt/bitnami/nginx/modules/ -la
total 884
drwxr-xr-x 1 www-data root   4096 Feb 25 16:56 .
drwxr-xr-x 1     1000 1000   4096 Feb 25 16:56 ..
-rwxr-xr-x 1 www-data root 711544 Feb 25 16:44 ngx_http_brotli_filter_module.so
-rwxr-xr-x 1 www-data root  14696 Feb 25 16:44 ngx_http_brotli_static_module.so
-rwxr-xr-x 1 www-data root  18808 Feb 25 16:44 ngx_http_geoip2_module.so
-rwxr-xr-x 1 www-data root  31688 Feb 25 16:44 ngx_http_modsecurity_module.so
-rwxr-xr-x 1 www-data root  89016 Feb 25 16:44 ngx_http_opentracing_module.so
-rwxr-xr-x 1 www-data root  18696 Feb 25 16:44 ngx_stream_geoip2_module.so
```

As you can see, the module is present. If you continue finding issues, do not hesitate to re-open the ticket.

**Comment by aeimer** [comment]
@javsalgar oh hey nice! This is ver goo news! Thank you!
I will try it out :)

**Comment by aeimer** [comment]
I was able to use it, thanks a lot!

**Comment by javsalgar** [comment]
Awesome!
