### ISSUE TITLE
tag 0.48.1 should use nginx v1.20.1

### ISSUE THREAD

**Issue by guillaumelamirand** [bitnami/bitnami-docker-nginx-ingress-controller#12]
**Description**
k8s nginx ingress 0.48.1 is built with nginx 1.20.1 since tag 0.47.0 see here: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.47.0

However latest tag of bitnami image contains nginx in 1.19.10.

**Steps to reproduce the issue:**

1. docker run --rm bitnami/nginx-ingress-controller:0.48.1-debian-10-r10 -version
![image](https://user-images.githubusercontent.com/4324887/127295982-a7b7b2e8-584b-40b5-85a2-0d74245779b9.png)

2. docker run --rm k8s.gcr.io/ingress-nginx/controller:v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c
303899 nginx -version
![image](https://user-images.githubusercontent.com/4324887/127295946-c8537ed8-cfb0-4076-a19b-17fa51175092.png)

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 24
  Running: 7
  Paused: 0
  Stopped: 17
 Images: 1060
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: ASUV:XG2U:VZHS:FK2E:HPFU:UQJZ:72RV:QUX6:Q6V6:EV7P:HJOM:TDJQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 98
  Goroutines: 91
  System Time: 2021-07-28T09:08:59.37225Z
  EventsListeners: 5
 Username: streamdataiodev
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by alemorcuq** [comment]
Thanks for the heads up, @guillaumelamirand. I will create an internal task to upgrade the version.

**Comment by dominiquemongelli** [comment]
Hi @alemorcuq, any update on that topic ?

**Comment by juan131** [comment]
I'm afraid there are now updated, I'll try to raise the priority of the associated task

**Comment by dominiquemongelli** [comment]
Hey @juan131 any news or target date ?

**Comment by juan131** [comment]
Hi @dominiquemongelli 

We'll update the NGINX dependency in the new major version release: `1.0.0`. The team is working on adapting our container and chart for this new major and soon you'll have news about this.

**Comment by dominiquemongelli** [comment]
Ok @juan131, thanks for your answer.
Do you know if a 0.49 is planned ? Looking at supported version of ingress-nginx-controller it should integrate nginx 1.20.1 : https://github.com/kubernetes/ingress-nginx#support-versions-table.
Do you have any target date for the 1.0.0 ?
Thank you.

**Comment by juan131** [comment]
Hi @guillaumelamirand 

AFAIK the team is now focused on the **1.0.0** release and it's very likely there will be no release for **0.49**. Regarding the target date for **1.0.0*, I'm afraid I can't give you any ETA since it can vary a lot depending on how many changes were included affecting the compilation, configuration, etc.

**Comment by dominiquemongelli** [comment]
Hi  @juan131.
Ok thanks for the info.
I suppose releasing a 0.49.0 will depend on any upcoming critical vulnerabilities. Am I right ?

**Comment by juan131** [comment]
Hi @dominiquemongelli 

One of my colleagues just confirmed that version **0.49.0** will be also released once they solve an issue in the compilation they're currently struggling with.

**Comment by dominiquemongelli** [comment]
That's a good news. We'll keep an eye on the upcoming release. Thanks!

**Comment by FraPazGal** [comment]
Hello @guillaumelamirand,

Both NGINX Ingress Controller's latest branches (0.49.0) and (1.0.0) have now been released, with the chart having being updated to version 1.0.0.

Thanks for the patience!

**Comment by guillaumelamirand** [comment]
@FraPazGal Great news! Thanks.
