### ISSUE TITLE
Missing symlinks to tracing libraries

### ISSUE THREAD

**Issue by NeonSludge** [bitnami/bitnami-docker-nginx-ingress-controller#13]
**Description**

The `bitnami/nginx-ingress-controller:0.48.1-debian-10-r0` image is missing symlinks to various tracing related libraries in `/usr/local/lib` which is where ingress-nginx tries to load them from when OpenTracing support is enabled. The libraries themselves are located in `/opt/bitnami/common/lib/`.

**Steps to reproduce the issue:**

1. Install the `nginx-ingress-controller` Helm chart from the Bitnami repository.
2. Enable OpenTracing support by adding `enable-opentracing: "true"` to the controller configuration as per the [official documentation](https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/).
3. Observe shared object loading failures in Nginx logs.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
2021/08/02 06:23:21 [error] 78513#78513: Failed to load tracing library /usr/local/lib/libzipkin_opentracing_plugin.so: /usr/local/lib/libzipkin_opentracing_plugin.so: cannot open shared object file: No such file or directory
nginx: [error] Failed to load tracing library /usr/local/lib/libzipkin_opentracing_plugin.so: /usr/local/lib/libzipkin_opentracing_plugin.so: cannot open shared object file: No such file or directory
nginx: configuration file /tmp/nginx-cfg043871901 test failed
```

**Version**
Bitnami `nginx-ingress-controller` chart version: `7.6.17`
Controller image: `docker.io/bitnami/nginx-ingress-controller:0.48.1-debian-10-r0`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes version: `v1.21.3`
Container runtime: containerd (no Docker)

**Comment by pablogalegoc** [comment]
Hi @NeonSludge,

I see we are adding a symlink to the `lua` subdirectory but not to the parent
https://github.com/bitnami/bitnami-docker-nginx-ingress-controller/blob/29e8839e973dd5527b70e8cb12ebd1596166aa55/0/debian-10/Dockerfile#L33

However I tried to reproduce the issue with the [Zipkin example](https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/#zipkin) (changing some `apiVersion` parameters since they seem a bit outdated) and couldn't see the error. Would you paste here the parameters and commands you used to enable OpenTracing support?

**Comment by NeonSludge** [comment]
> Would you paste here the parameters and commands you used to enable OpenTracing support?

Sure, here is the easiest way to reproduce this problem:

1. Get a Kubernetes cluster.
2. Add Helm repository:
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami`
```

3. Prepare a basic `values.yaml` file:
```
$ cat ./values.yaml
service:
  type: ClusterIP # just for testing purposes

podSecurityPolicy:
  enabled: true # not needed if your cluster is not PSP-enabled

config:
  enable-opentracing: "true"
  zipkin-collector-host: "zipkin.default.svc.cluster.local"
```

4. Create a new namespace and install the `bitnami/nginx-ingress-controller` chart:
```
$ kubectl create ns ingress-opentracing
$ helm install ingress-opentracing bitnami/nginx-ingress-controller -n ingress-opentracing -f ./values.yaml
``` 

5. View controller's logs:
```
$ kubectl logs -n ingress-opentracing deployment/ingress-opentracing-nginx-ingress-controller
...
2021/08/02 16:27:41 [error] 34#34: Failed to load tracing library /usr/local/lib/libzipkin_opentracing_plugin.so: /usr/local/lib/libzipkin_opentracing_plugin.so: cannot open shared object file: No such file or directory
nginx: [error] Failed to load tracing library /usr/local/lib/libzipkin_opentracing_plugin.so: /usr/local/lib/libzipkin_opentracing_plugin.so: cannot open shared object file: No such file or directory
nginx: configuration file /tmp/nginx-cfg115155268 test failed
...

```

We've tried building a custom container image for the controller with all libraries from `/opt/bitnami/common/lib` symlinked into `/usr/local/lib`: this fixes the problem and the ingress-controller (including the OpenTracing plugin) works perfectly.

**Comment by pablogalegoc** [comment]
Wow @NeonSludge, thank you so much for all the detail! I've reproduced the bug right away with your instructions. I'm going to open an internal task to look into this because we will probably need a folder reorganization to avoid symlinking every library. Thanks for flagging this!
