### ISSUE TITLE
Support for service-upstream?

### ISSUE THREAD

**Issue by pjotre86** [bitnami/bitnami-docker-nginx-ingress-controller#17]
### Name and Version

bitnami/bitnami-docker-nginx-ingress-controller

### What is the problem this feature will solve?

Hey!
I'm wondering if the bitnami docker-image/helm-chart supports the `nginx.ingress.kubernetes.io/service-upstream` annotation. Here's the official documentation of that annotation:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#service-upstream
I tried adding it, but it looks like the ingress-controller ignores it.
Thanks for any hints in advance!

### What is the feature you are proposing to solve the problem?

Add support for `nginx.ingress.kubernetes.io/service-upstream` annotation.

**Comment by rthamrin** [comment]
have you check your ingress?

```
kubectl describe ingress [youringressname] -n [yournamespace]
```

it should be an annotation service upstream there. but me also still confusing.

anyway check this out, how to implement

https://kubernetes.github.io/ingress-nginx/examples/chashsubset/deployment.yaml

**Comment by alemorcuq** [comment]
It should work, unless there's something that must be enabled at build time and we haven't, but it doesn't seem to be the case here.
