### ISSUE TITLE
0.25.x releases missing

### ISSUE THREAD

**Issue by jjo** [bitnami/bitnami-docker-nginx-ingress-controller#5]
nginx-ingress-controller v0.25.1 which fixes several CVEs is already available at https://github.com/kubernetes/ingress-nginx/releases, while https://hub.docker.com/r/bitnami/nginx-ingress-controller/tags shows latest ones at 0.24.x.

**Comment by alemorcuq** [comment]
Hi, @jjo.

We are currently working on it, we will release it as soon as possible.

Regards,
Alejandro

**Comment by marcosbc** [comment]
Hi @jjo, it was just released. The specific Debian tag is `0.25.1-debian-9-r0`.

**Comment by jjo** [comment]
@marcosbc 
FYI just tried `bitnami/nginx-ingress-controller:0.25.1-debian-9-r3` (built 1hr ago~ish)
without changing any fields from above deployment manifest, but it's still failing with:
```
I0829 20:21:49.674013       1 controller.go:133] Configuration changes detected, backend reload required.
E0829 20:21:49.874774       1 controller.go:145] Unexpected failure reloading the backend:
open /etc/nginx/nginx.conf: permission denied
W0829 20:21:49.874802       1 queue.go:130] requeuing bitnami-cms/preview, err open /etc/nginx/nginx.conf: permission denied
```
