### ISSUE TITLE
Support for RHEL based images

### ISSUE THREAD

**Issue by sandeep-bangera** [bitnami/bitnami-docker-nginx-ingress-controller#8]
**Description**

Feature request: Is there a plan to support RHEL images?.  The last one available is `0.24.1-rhel-7-r2`

**Steps to reproduce the issue:**

N/A
**Describe the results you received:**

N/A
**Describe the results you expected:**

N/A

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Version**

- Output of `docker version`:

```
N/A
```

- Output of `docker info`:

```
N/A
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @sandeep-bangera.

At the moment we only support Debian 9 and Oracle Linux 7, and we are working on supporting Debian 10. For other base images, including custom base images, there is Project Galleon. You can read more about it here: https://bitnami.com/enterprise-catalog
