### ISSUE TITLE
nginx-ingress-controller should package nginx 1.17.6

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-nginx-ingress-controller#9]
**Description**

In BKPR we use the `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol` annotation for [PROXY protocol support on AWS](https://kubernetes.io/docs/concepts/services-networking/service/#proxy-protocol-support-on-aws). The recent versions of ingress-nginx add the nginx configuration parameter `proxy_protocol_server_port` when this annotation is specified. The `proxy_protocol_server_port` was added to nginx in release `1.17.6` (see: https://nginx.org/en/docs/http/ngx_http_core_module.html). 

The nginx version packaged in this docker image appears to be `nginx version: openresty/1.15.8.1` which does not have the required option and as a result the container crashes as it fails to pass the nginx config test.

```
# ./nginx -v
nginx version: openresty/1.15.8.1
```

> The upstream nginx-ingress-controller image packages `nginx/1.17.7`
>
> ```bash
> # docker run -it --rm quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.28.0 nginx -v
> nginx version: nginx/1.17.7
> ```

**Steps to reproduce the issue:**

Deploy BKPR with https://github.com/bitnami/kube-prod-runtime/pull/723 on a EKS cluster.

[BKPR EKS Quickstart ](https://github.com/bitnami/kube-prod-runtime/blob/master/docs/quickstart-eks.md)

**Describe the results you received:**

NGINX Ingress Controller pods enter a crash loop.

**Describe the results you expected:**

NGINX Ingress Controller pods are started normally and all ingress endpoints are accessible.

**Comment by rafariossaa** [comment]
Hi @sameersbn ,
  Will you send a patch to fix the issue ?

**Comment by sameersbn** [comment]
I believe this issue has to be fixed in the nginx-ingress-controller nami module. From what I have found https://github.com/openresty/openresty/releases/tag/v1.15.8.2 is the last release. I believe the nginx-ingress-controller should probably remove openresty package and use the upstream nginx package instead.

>  Will you send a patch to fix the issue ?
I am not familiar with the nginx-ingress compilation and why openresty is being used. I'd prefer if someone familiar with nginx-ingress to look into this change.

**Comment by rafariossaa** [comment]
I am creating an internal task to study this request.
 
We will come back when we have news.

**Comment by javsalgar** [comment]
Closing this issue as the image was released (`-r67`)
